<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BranchSeeder extends Seeder
{
    public function run(): void
    {
        $branches = [
            ['branch_code' => 'BOHL',   'branch_name' => 'BOHOL LOGISTICS',     'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALAD',   'branch_name' => 'ALANO',               'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'AURD',   'branch_name' => 'AURORA',              'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BALD',   'branch_name' => 'BALINGASAG',          'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BONI',   'branch_name' => 'BONIFACIO',           'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BUUD',   'branch_name' => 'BUUG',                'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALD',   'branch_name' => 'CALAMBA',             'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CAMD',   'branch_name' => 'CAMINO NUEVO',        'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DAPI',   'branch_name' => 'DAPITAN',             'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIPD',   'branch_name' => 'DIPOLOG',             'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIPD2',  'branch_name' => 'DIPOLOG 2',           'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ILID',   'branch_name' => 'ILIGAN',              'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'IMED',   'branch_name' => 'IMELDA',              'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'INIT2',  'branch_name' => 'INITAO',              'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'IPID',   'branch_name' => 'IPIL',                'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'JIME',   'branch_name' => 'JIMENEZ',             'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KABD',   'branch_name' => 'KABASALAN',           'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LABD',   'branch_name' => 'LABASON',             'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LILD',   'branch_name' => 'LILOY',               'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANO',   'branch_name' => 'MANOLO FORTICH',      'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARA2',  'branch_name' => 'MARAMAG',             'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARD',   'branch_name' => 'MARANDING',           'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLD',   'branch_name' => 'MOLAVE',              'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLD2',  'branch_name' => 'MOLAVE 2',            'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'NUND2',  'branch_name' => 'NUÑEZ 2',             'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OROD',   'branch_name' => 'OROQUIETA',           'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OZAD',   'branch_name' => 'OZAMIZ',              'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'RIZD',   'branch_name' => 'OZAMIZ (Rizal)',      'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PUTD',   'branch_name' => 'PUTIK',               'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SANM',   'branch_name' => 'SAN MIGUEL',          'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SIND',   'branch_name' => 'SINDANGAN',           'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SUCD',   'branch_name' => 'SUCABON',             'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TUBOD',  'branch_name' => 'TUBOD',               'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VITA',   'branch_name' => 'VITALI',              'branch' => 'Des Appliance Plaza, Inc.', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'AURO',   'branch_name' => 'AURORA',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BALA',   'branch_name' => 'BALANGASAN',          'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BUHA',   'branch_name' => 'BUHANGIN',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMBL',  'branch_name' => 'BULUA',               'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BULU',   'branch_name' => 'BULUA 2',             'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMC',   'branch_name' => 'CAGAYAN',             'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMCA',  'branch_name' => 'CALAMBA',             'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMCDO', 'branch_name' => 'CARMEN CDO',         'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CATM',   'branch_name' => 'CATMON 2',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CERI',   'branch_name' => 'CERILLES PAGADIAN',   'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIGOS',  'branch_name' => 'DIGOS',               'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMD',   'branch_name' => 'DIPOLOG',             'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMD2',  'branch_name' => 'DIPOLOG 2',           'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DONC',   'branch_name' => 'DON CARLOS',          'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ELSA',   'branch_name' => 'EL SALVADOR',         'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ILIG',   'branch_name' => 'ILIGAN',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'JIMEDSM', 'branch_name' => 'JIMENEZ',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KABA2',  'branch_name' => 'KABASALAN',           'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KATI',   'branch_name' => 'KATIPUNAN',           'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LABA',   'branch_name' => 'LABASON',             'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARA',   'branch_name' => 'MARAMAG',             'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MATI',   'branch_name' => 'MATINA',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MING',   'branch_name' => 'MINGLANILLA',         'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMM',   'branch_name' => 'MOLAVE',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMPO',  'branch_name' => 'PANABO',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'RIZA',   'branch_name' => 'RIZAL PAGADIAN',      'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TOMAS', 'branch_name' => 'SANTO TOMAS',          'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMSO',  'branch_name' => 'SUZUKI (OZAMIZ)',     'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TACU',   'branch_name' => 'TACURONG',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMT',   'branch_name' => 'TAGBILARAN',          'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMT2',  'branch_name' => 'TAGBILARAN 2',        'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMTG',  'branch_name' => 'TAGUM',               'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TORI',   'branch_name' => 'TORIL',               'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMV',   'branch_name' => 'VALENCIA',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VILLA',  'branch_name' => 'VILLANUEVA',          'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMAO',  'branch_name' => 'ARGAO',               'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMBN',  'branch_name' => 'BALAMBAN',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMB',   'branch_name' => 'BASAK',               'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BOGO',   'branch_name' => 'BOGO MULTI',          'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALIN',  'branch_name' => 'CALINOG Y3S',         'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMA',   'branch_name' => 'CAMBARO',             'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARC',   'branch_name' => 'CARCAR',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARC2',  'branch_name' => 'CARCAR 2',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMDN',  'branch_name' => 'CARMEN',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMC2', 'branch_name' => 'CARMEN 2',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMCN',  'branch_name' => 'CATMON',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'COMPO',  'branch_name' => 'COMPOSTELA',          'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMP',   'branch_name' => 'CONSOLACION',         'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DAAN',   'branch_name' => 'DAANBANTAYAN 2',      'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DANAO',  'branch_name' => 'DANAO',               'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ILOI',   'branch_name' => 'ILOILO',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMK',   'branch_name' => 'LABANGON',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LAPU',   'branch_name' => 'LAPU-LAPU 2',         'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMLN',  'branch_name' => 'LILOAN',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MAND',   'branch_name' => 'MANDAUE MULTI',       'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MAND2',  'branch_name' => 'MANDAUE Y3S',         'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MEDE',   'branch_name' => 'MEDELLIN',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PARD',   'branch_name' => 'PARDO',               'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PARD2',  'branch_name' => 'PARDO 2 SUZUKI 3S',   'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'REMI',   'branch_name' => 'SAN REMIGIO',         'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'REMI2',  'branch_name' => 'SAN REMIGIO 2',       'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMTA',  'branch_name' => 'TALAMBAN',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSML',   'branch_name' => 'TOLEDO',              'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMDM',  'branch_name' => 'TOLEDO 2',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TUBU',   'branch_name' => 'TUBURAN',             'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'UBAY',   'branch_name' => 'UBAY',                'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BOLOD',  'branch_name' => 'BOLOD',               'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CATAR2', 'branch_name' => 'CATARMAN',            'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MONKA',  'branch_name' => 'MONKAYO',             'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALAH',   'branch_name' => 'ALANO',               'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'AURH',   'branch_name' => 'AURORA',              'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BUUH',   'branch_name' => 'BUUG',                'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALA',   'branch_name' => 'CALAMBA',             'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CAMH',   'branch_name' => 'CAMINO NUEVO',        'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DATH',   'branch_name' => 'DATOC',               'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GENT',   'branch_name' => 'GENERAL TRIAS',       'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GUSA',   'branch_name' => 'GUSA',                'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'INIT',   'branch_name' => 'INITAO',              'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'IPIH',   'branch_name' => 'IPIL',                'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KABA',   'branch_name' => 'KABASALAN',           'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARH',   'branch_name' => 'MARANDING',           'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLH',   'branch_name' => 'MOLAVE',              'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OROH',   'branch_name' => 'OROQUIETA',           'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OROH2',  'branch_name' => 'OROQUIETA 2',         'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OZAH',   'branch_name' => 'OZAMIZ',              'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SINDA',  'branch_name' => 'SINDANGAN',           'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VETH',   'branch_name' => 'VETERANS',            'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VILLA2', 'branch_name' => 'VILLANUEVA',          'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BALAM',  'branch_name' => 'BALAMBAN',            'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALIN2', 'branch_name' => 'CALINOG',             'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMC',  'branch_name' => 'CARMEN',              'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PARD3',  'branch_name' => 'PARDO',               'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'HO',     'branch_name' => 'HEAD OFFICE',         'branch' => 'Head Office',      'acronym' => 'HO', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'INAB',   'branch_name' => 'INABANGA',            'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TANH',   'branch_name' => 'TANZA',               'branch' => 'Honda Des, Inc.', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BOHK',   'branch_name' => 'KIA BOHOL',           'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'KIA', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SALA',   'branch_name' => 'ALANO',               'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALI',   'branch_name' => 'CALINAN',             'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SMCT',   'branch_name' => 'IPIL',                'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MALA',   'branch_name' => 'MALAYBALAY',          'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLS',   'branch_name' => 'MOLAVE',              'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SDIP',   'branch_name' => 'TURNO',               'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'AKLA',   'branch_name' => 'AKLAN',               'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALIC',   'branch_name' => 'ALICIA',              'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALEN',   'branch_name' => 'ALLEN',               'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ANTIP',  'branch_name' => 'ANTIPOLO',            'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ANTI',   'branch_name' => 'ANTIQUE',             'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SARG',   'branch_name' => 'ARGAO',               'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BANTA',  'branch_name' => 'BANTAYAN',            'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BAYB',   'branch_name' => 'BAYBAY',              'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BINAN',  'branch_name' => 'BINAN',               'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALAP',  'branch_name' => 'CALAPE',              'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALAP2', 'branch_name' => 'CALAPE 2',            'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARS',   'branch_name' => 'CARCAR',              'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMB',  'branch_name' => 'CARMEN',              'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMO',  'branch_name' => 'CARMONA',             'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CATAR',  'branch_name' => 'CATARMAN',            'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DASMA',  'branch_name' => 'DASMARIÑAS',          'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'FAMY',   'branch_name' => 'FAMY',                'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GUIN',   'branch_name' => 'GUINDULMAN',          'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GUIN2',  'branch_name' => 'GUINDULMAN 2',        'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'JAGN',   'branch_name' => 'JAGNA',               'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SLAP',   'branch_name' => 'LAPU-LAPU',           'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SLIL',   'branch_name' => 'LILOAN',              'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LIPA',   'branch_name' => 'LIPA',                'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LOAY',   'branch_name' => 'LOAY',                'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CAGL',   'branch_name' => 'LOGISTICS',           'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIPL',   'branch_name' => 'LOGISTICS 2',         'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OZAL',   'branch_name' => 'LOGISTICS 3',         'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ZAML',   'branch_name' => 'LOGISTICS 4',         'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANL',   'branch_name' => 'LOGISTICS MANDAUE',   'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MADRI',  'branch_name' => 'MADRIDEJOS',          'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANG',   'branch_name' => 'MANGA',               'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'NAIC',   'branch_name' => 'NAIC',                'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PAGS',   'branch_name' => 'PAGSANJAN',           'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SROS',   'branch_name' => 'ROSARIO',             'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SAGBA',  'branch_name' => 'SAGBAYAN',            'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SANJ',   'branch_name' => 'SAN JOSE',            'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SANP',   'branch_name' => 'SAN PEDRO',           'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SANT2',  'branch_name' => 'SANTANDER 2',         'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SILA',   'branch_name' => 'SILANG',              'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TALI',   'branch_name' => 'TALIBON',             'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TALI2',  'branch_name' => 'TALIBON 2',           'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TANZ',   'branch_name' => 'TANZA',               'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TANZ2',  'branch_name' => 'TANZA 2',             'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TRINI',  'branch_name' => 'TRINIDAD',            'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TRINI2', 'branch_name' => 'TRINIDAD 2',          'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TUBI',   'branch_name' => 'TUBIGON',             'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VALEN',  'branch_name' => 'VALENCIA',            'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'YATI',   'branch_name' => 'YATI LILOAN',         'branch' => 'Strong Moto Centrum, Inc.', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANP',   'branch_name' => 'SURPLUS CAR PRODUCTION', 'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMSB',  'branch_name' => 'SUZUKI AUTO BOHOL',   'branch' => 'Des Strong Motors, Inc.', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
        ];

        DB::table('branches')->insert($branches);
    }
}
