<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BranchSeeder extends Seeder
{
    public function run(): viod
    {
        $branches = [
            ['branch_code' => 'BOHL', 'branch_name' => 'BOHOL LOGISTICS', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALAD', 'branch_name' => 'ALANO', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'AURD', 'branch_name' => 'AURORA', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BALD', 'branch_name' => 'BALINGASAG', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BONI', 'branch_name' => 'BONIFACIO', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BUUD', 'branch_name' => 'BUUG', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALD', 'branch_name' => 'CALAMBA', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CAMD', 'branch_name' => 'CAMINO NUEVO', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DAPI', 'branch_name' => 'DAPITAN', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIPD', 'branch_name' => 'DIPOLOG', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIPD2', 'branch_name' => 'DIPOLOG 2', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ILID', 'branch_name' => 'ILIGAN', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'IMED', 'branch_name' => 'IMELDA', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'INIT2', 'branch_name' => 'INITAO', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'IPID', 'branch_name' => 'IPIL', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'JIME', 'branch_name' => 'JIMENEZ', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KABD', 'branch_name' => 'KABASALAN', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LABD', 'branch_name' => 'LABASON', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LILD', 'branch_name' => 'LILOY', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANO', 'branch_name' => 'MANOLO FORTICH', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARA2', 'branch_name' => 'MARAMAG', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARD', 'branch_name' => 'MARANDING', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLD', 'branch_name' => 'MOLAVE', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLD2', 'branch_name' => 'MOLAVE 2', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'NUND2', 'branch_name' => 'NUÑEZ 2', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OROD', 'branch_name' => 'OROQUIETA', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OZAD', 'branch_name' => 'OZAMIZ', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'RIZD', 'branch_name' => 'OZAMIZ (Rizal)', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PUTD', 'branch_name' => 'PUTIK', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SANM', 'branch_name' => 'SAN MIGUEL', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SIND', 'branch_name' => 'SINDANGAN', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SUCD', 'branch_name' => 'SUCABON', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TUBOD', 'branch_name' => 'TUBOD', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VITA', 'branch_name' => 'VITALI', 'acronym' => 'DAP', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'AURO', 'branch_name' => 'AURORA', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BALA', 'branch_name' => 'BALANGASAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BUHA', 'branch_name' => 'BUHANGIN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMBL', 'branch_name' => 'BULUA', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BULU', 'branch_name' => 'BULUA 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMC', 'branch_name' => 'CAGAYAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMCA', 'branch_name' => 'CALAMBA', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMCDO', 'branch_name' => 'CARMEN CDO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CATM', 'branch_name' => 'CATMON 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CERI', 'branch_name' => 'CERILLES PAGADIAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIGOS', 'branch_name' => 'DIGOS', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMD', 'branch_name' => 'DIPOLOG', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMD2', 'branch_name' => 'DIPOLOG 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DONC', 'branch_name' => 'DON CARLOS', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ELSA', 'branch_name' => 'EL SALVADOR', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ILIG', 'branch_name' => 'ILIGAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'JIMEDSM', 'branch_name' => 'JIMENEZ', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KABA2', 'branch_name' => 'KABASALAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KATI', 'branch_name' => 'KATIPUNAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LABA', 'branch_name' => 'LABASON', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARA', 'branch_name' => 'MARAMAG', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MATI', 'branch_name' => 'MATINA', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MING', 'branch_name' => 'MINGLANILLA', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMM', 'branch_name' => 'MOLAVE', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMPO', 'branch_name' => 'PANABO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'RIZA', 'branch_name' => 'RIZAL PAGADIAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TOMAS', 'branch_name' => 'SANTO TOMAS', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMSO', 'branch_name' => 'SUZUKI (OZAMIZ)', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TACU', 'branch_name' => 'TACURONG', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMT', 'branch_name' => 'TAGBILARAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMT2', 'branch_name' => 'TAGBILARAN 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMTG', 'branch_name' => 'TAGUM', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TORI', 'branch_name' => 'TORIL', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMV', 'branch_name' => 'VALENCIA', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VILLA', 'branch_name' => 'VILLANUEVA', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMAO', 'branch_name' => 'ARGAO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMBN', 'branch_name' => 'BALAMBAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMB', 'branch_name' => 'BASAK', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BOGO', 'branch_name' => 'BOGO MULTI', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALIN', 'branch_name' => 'CALINOG Y3S', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMA', 'branch_name' => 'CAMBARO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARC', 'branch_name' => 'CARCAR', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARC2', 'branch_name' => 'CARCAR 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMDN', 'branch_name' => 'CARMEN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMC2', 'branch_name' => 'CARMEN 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMCN', 'branch_name' => 'CATMON', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'COMPO', 'branch_name' => 'COMPOSTELA', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMP', 'branch_name' => 'CONSOLACION', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DAAN', 'branch_name' => 'DAANBANTAYAN 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DANAO', 'branch_name' => 'DANAO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ILOI', 'branch_name' => 'ILOILO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMK', 'branch_name' => 'LABANGON', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LAPU', 'branch_name' => 'LAPU-LAPU 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMLN', 'branch_name' => 'LILOAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MAND', 'branch_name' => 'MANDAUE MULTI', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MAND2', 'branch_name' => 'MANDAUE Y3S', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MEDE', 'branch_name' => 'MEDELLIN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PARD', 'branch_name' => 'PARDO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PARD2', 'branch_name' => 'PARDO 2 SUZUKI 3S', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'REMI', 'branch_name' => 'SAN REMIGIO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'REMI2', 'branch_name' => 'SAN REMIGIO 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMTA', 'branch_name' => 'TALAMBAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSML', 'branch_name' => 'TOLEDO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMDM', 'branch_name' => 'TOLEDO 2', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TUBU', 'branch_name' => 'TUBURAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'UBAY', 'branch_name' => 'UBAY', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BOLOD', 'branch_name' => 'BOLOD', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CATAR2', 'branch_name' => 'CATARMAN', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MONKA', 'branch_name' => 'MONKAYO', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALAH', 'branch_name' => 'ALANO', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'AURH', 'branch_name' => 'AURORA', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BUUH', 'branch_name' => 'BUUG', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALA', 'branch_name' => 'CALAMBA', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CAMH', 'branch_name' => 'CAMINO NUEVO', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DATH', 'branch_name' => 'DATOC', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GENT', 'branch_name' => 'GENERAL TRIAS', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GUSA', 'branch_name' => 'GUSA', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'INIT', 'branch_name' => 'INITAO', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'IPIH', 'branch_name' => 'IPIL', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'KABA', 'branch_name' => 'KABASALAN', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MARH', 'branch_name' => 'MARANDING', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLH', 'branch_name' => 'MOLAVE', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OROH', 'branch_name' => 'OROQUIETA', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OROH2', 'branch_name' => 'OROQUIETA 2', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OZAH', 'branch_name' => 'OZAMIZ', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SINDA', 'branch_name' => 'SINDANGAN', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VETH', 'branch_name' => 'VETERANS', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VILLA2', 'branch_name' => 'VILLANUEVA', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BALAM', 'branch_name' => 'BALAMBAN', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALIN2', 'branch_name' => 'CALINOG', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMC', 'branch_name' => 'CARMEN', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PARD3', 'branch_name' => 'PARDO', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'HO', 'branch_name' => 'HEAD OFFICE', 'acronym' => 'HO', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'INAB', 'branch_name' => 'INABANGA', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TANH', 'branch_name' => 'TANZA', 'acronym' => 'HD', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BOHK', 'branch_name' => 'KIA BOHOL', 'acronym' => 'KIA', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SALA', 'branch_name' => 'ALANO', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALI', 'branch_name' => 'CALINAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SMCT', 'branch_name' => 'IPIL(TURNED HD WINGSHOP)', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MALA', 'branch_name' => 'MALAYBALAY', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MOLS', 'branch_name' => 'MOLAVE', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SDIP', 'branch_name' => 'TURNO', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'AKLA', 'branch_name' => 'AKLAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALIC', 'branch_name' => 'ALICIA', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ALEN', 'branch_name' => 'ALLEN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ANTIP', 'branch_name' => 'ANTIPOLO', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ANTI', 'branch_name' => 'ANTIQUE', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SARG', 'branch_name' => 'ARGAO', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BANTA', 'branch_name' => 'BANTAYAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BAYB', 'branch_name' => 'BAYBAY', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'BINAN', 'branch_name' => 'BINAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALAP', 'branch_name' => 'CALAPE', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CALAP2', 'branch_name' => 'CALAPE 2', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARS', 'branch_name' => 'CARCAR', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMB', 'branch_name' => 'CARMEN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CARMO', 'branch_name' => 'CARMONA', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CATAR', 'branch_name' => 'CATARMAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DASMA', 'branch_name' => 'DASMARIÑAS', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'FAMY', 'branch_name' => 'FAMY', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GUIN', 'branch_name' => 'GUINDULMAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'GUIN2', 'branch_name' => 'GUINDULMAN 2', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'JAGN', 'branch_name' => 'JAGNA', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SLAP', 'branch_name' => 'LAPU-LAPU', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SLIL', 'branch_name' => 'LILOAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LIPA', 'branch_name' => 'LIPA', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'LOAY', 'branch_name' => 'LOAY', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'CAGL', 'branch_name' => 'LOGISTICS', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DIPL', 'branch_name' => 'LOGISTICS 2', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'OZAL', 'branch_name' => 'LOGISTICS 3', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'ZAML', 'branch_name' => 'LOGISTICS 4', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANL', 'branch_name' => 'LOGISTICS MANDAUE', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MADRI', 'branch_name' => 'MADRIDEJOS', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANG', 'branch_name' => 'MANGA', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'NAIC', 'branch_name' => 'NAIC', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'PAGS', 'branch_name' => 'PAGSANJAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SROS', 'branch_name' => 'ROSARIO', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SAGBA', 'branch_name' => 'SAGBAYAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SANJ', 'branch_name' => 'SAN JOSE', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SANP', 'branch_name' => 'SAN PEDRO', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SANT2', 'branch_name' => 'SANTANDER 2', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'SILA', 'branch_name' => 'SILANG', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TALI', 'branch_name' => 'TALIBON', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TALI2', 'branch_name' => 'TALIBON 2', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TANZ', 'branch_name' => 'TANZA', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TANZ2', 'branch_name' => 'TANZA 2', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TRINI', 'branch_name' => 'TRINIDAD', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TRINI2', 'branch_name' => 'TRINIDAD 2', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'TUBI', 'branch_name' => 'TUBIGON', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'VALEN', 'branch_name' => 'VALENCIA', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'YATI', 'branch_name' => 'YATI LILOAN', 'acronym' => 'SMCT', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'MANP', 'branch_name' => 'SURPLUS CAR PRODUCTION', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
            ['branch_code' => 'DSMSB', 'branch_name' => 'SUZUKI AUTO BOHOL', 'acronym' => 'DSM', 'created_at' => now(), 'updated_at' => now()],
        ];
        
        DB::table('branches')->insert($branches);
    }
}